require('dotenv').config();
const mongoose = require('mongoose');
const slugify = require('slugify');

async function seedDatabase(force = false) {
  if (mongoose.connection.readyState === 0) {
    const mongoUri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/tantvani';
    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB for Seeding...');
  }

  const User = require('../models/User');
  const Category = require('../models/Category');
  const Product = require('../models/Product');

  const existingCount = await Product.countDocuments();
  if (!force && existingCount > 0) {
    console.log(`ℹ️ Database already has ${existingCount} products. Skipping seed.`);
    return;
  }

  if (force) {
    // Clear existing products & categories to re-seed cleanly
    await Product.deleteMany({});
    await Category.deleteMany({});
    console.log('🧹 Cleared existing Products and Categories');
  }

  // 1. Ensure Admin User
  let admin = await User.findOne({ email: 'admin@tantvani.com' });
  if (!admin) {
    admin = await User.create({
      name: 'Tantvani Admin',
      email: 'admin@tantvani.com',
      password: 'Admin@123',
      role: 'admin',
    });
    console.log('✅ Created Admin user');
  } else {
    admin.password = 'Admin@123';
    admin.role = 'admin';
    await admin.save();
    console.log('✅ Ensured Admin user');
  }

  // 2. Create Categories
  const categoryData = [
    {
      name: 'Banarasi Sarees',
      description: 'Intricate Kadwa, Katan, and Cutwork silk sarees handwoven in the holy city of Varanasi.',
      image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop&cat=1',
      sortOrder: 1,
    },
    {
      name: 'Kanjivaram Silk',
      description: 'Lustrous mulberry silk sarees with heavy pure gold and silver Zari temple borders from Kanchipuram.',
      image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop&cat=2',
      sortOrder: 2,
    },
    {
      name: 'Chanderi & Maheshwari',
      description: 'Sheer lightweight silk-cottons featuring signature coin, floral, and peacock bootis.',
      image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop&cat=3',
      sortOrder: 3,
    },
    {
      name: 'Organza & Tussar',
      description: 'Delicate hand-painted organzas and rich textured wild Tussar silks with rustic charm.',
      image: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=1000&auto=format&fit=crop&cat=4',
      sortOrder: 4,
    },
    {
      name: 'Cotton & Linen',
      description: 'Handspun Bengal jamdanis, breathable linens, and everyday handloom luxury.',
      image: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?q=80&w=1000&auto=format&fit=crop&cat=5',
      sortOrder: 5,
    },
    {
      name: 'Heritage Bridal',
      description: 'Royal bridal trousseau weaves adorned with gold brocades, meenakari, and rich pallus.',
      image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1000&auto=format&fit=crop&cat=6',
      sortOrder: 6,
    },
  ];

  const categoryDocs = {};
  for (const cat of categoryData) {
    const createdCat = await Category.create(cat);
    categoryDocs[cat.name] = createdCat;
    console.log(`✅ Category: ${cat.name}`);
  }

  // 3. High quality real Saree images list (Curated Unsplash imagery)
  const imgList = [
    'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1604014237800-1c9102c219da?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1520975661595-6453be3f7070?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1550614000-4895a10e1bfd?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1572804013427-4d7ca7268217?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1554412933-514a83d2f3c8?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1560060141-7b9018741ced?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1588516903720-8ceb67f9ef84?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1590736704728-f4730bb30770?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1608234807905-4466023792f5?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1624224971170-2f84fed5eb5e?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1626497764746-6dc36546b388?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1627384113743-6bd5a479fffd?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1629198688000-71f23e745b6e?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1513094735237-8f2714d57c13?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1604014237800-1c9102c219da?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop&v=1',
    'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1000&auto=format&fit=crop&v=1',
  ];

  // 4. 40 Realistic Luxury Saree Data
  const products = [
    // --- Banarasi Sarees (1-8) ---
    {
      name: 'Royal Crimson Kadwa Zari Katan Silk Banarasi Saree',
      category: categoryDocs['Banarasi Sarees']._id,
      price: 48500,
      discountPrice: 42999,
      fabric: 'Katan Silk',
      work: 'Kadwa Weave & Gold Zari',
      origin: 'Varanasi, Uttar Pradesh',
      occasion: ['Wedding', 'Bridal', 'Festive'],
      color: ['Crimson Red', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 12,
      sku: 'TANT-BAN-001',
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Handwoven pure Katan silk Saree in deep crimson red with classic Mughal floral Kadwa motifs.',
      description: 'An heirloom masterpiece woven over 45 days by master artisans in Varanasi. Made from 100% mulberry Katan silk, featuring detailed gold zari bootis across the body and an ornate pallu with traditional peacock motifs.',
      care: 'Dry clean only. Store wrapped in a muslin cloth in a cool, dry place.',
      images: [
        { url: imgList[0], alt: 'Royal Crimson Banarasi Saree Front' },
        { url: imgList[1], alt: 'Royal Crimson Banarasi Saree Pallu Detail' },
      ],
    },
    {
      name: 'Emerald Green Meenakari Brocade Banarasi Saree',
      category: categoryDocs['Banarasi Sarees']._id,
      price: 36000,
      discountPrice: 31500,
      fabric: 'Banarasi Silk',
      work: 'Meenakari Brocade',
      origin: 'Varanasi, Uttar Pradesh',
      occasion: ['Festive', 'Party', 'Wedding'],
      color: ['Emerald Green', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 8,
      sku: 'TANT-BAN-002',
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Lustrous emerald green silk brocade accented with colorful enamel Meenakari floral motifs.',
      description: 'Radiating timeless elegance, this Emerald Green Banarasi saree features fine silver and gold zari weave interwoven with subtle Meenakari threadwork. Perfect for grand evening receptions and festive celebrations.',
      care: 'Dry clean only. Do not iron directly on zari.',
      images: [
        { url: imgList[2], alt: 'Emerald Green Banarasi Saree' },
        { url: imgList[3], alt: 'Emerald Green Banarasi Saree Border' },
      ],
    },
    {
      name: 'Midnight Blue Jangla Cutwork Banarasi Saree',
      category: categoryDocs['Banarasi Sarees']._id,
      price: 52000,
      discountPrice: 46800,
      fabric: 'Pure Katan Silk',
      work: 'Jangla Weave',
      origin: 'Varanasi, Uttar Pradesh',
      occasion: ['Wedding', 'Bridal'],
      color: ['Midnight Blue', 'Silver'],
      length: 6.3,
      blouseIncluded: true,
      stock: 6,
      sku: 'TANT-BAN-003',
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Deep navy midnight blue silk covered in intricate silver floral vine Jangla weave.',
      description: 'The Jangla weave is one of Varanasi’s oldest weaving art forms. This saree features dense silver bullion threads interwoven into continuous floral creepers along the entire drape.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[4], alt: 'Midnight Blue Banarasi Saree' },
        { url: imgList[5], alt: 'Midnight Blue Banarasi Saree Detail' },
      ],
    },
    {
      name: 'Rani Pink Organza Tissue Banarasi Saree',
      category: categoryDocs['Banarasi Sarees']._id,
      price: 28500,
      discountPrice: 24900,
      fabric: 'Organza Silk',
      work: 'Tissue Zari Weave',
      origin: 'Varanasi, Uttar Pradesh',
      occasion: ['Festive', 'Party'],
      color: ['Rani Pink', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 15,
      sku: 'TANT-BAN-004',
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Airy, delicate Rani pink tissue organza with luminous gold sheen and border.',
      description: 'Lightweight yet regal, this Rani Pink Organza Tissue saree pairs modern translucency with rich Banarasi heritage borders.',
      care: 'Dry clean only. Steam iron only.',
      images: [
        { url: imgList[6], alt: 'Rani Pink Organza Banarasi Saree' },
        { url: imgList[7], alt: 'Rani Pink Saree Closeup' },
      ],
    },
    {
      name: 'Antique Gold Georgette Khaddi Banarasi Saree',
      category: categoryDocs['Banarasi Sarees']._id,
      price: 32000,
      discountPrice: 28900,
      fabric: 'Khaddi Georgette',
      work: 'Zari Jaal',
      origin: 'Varanasi, Uttar Pradesh',
      occasion: ['Party', 'Wedding', 'Festive'],
      color: ['Gold', 'Beige'],
      length: 6.3,
      blouseIncluded: true,
      stock: 10,
      sku: 'TANT-BAN-005',
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Flowing handloom Khaddi Georgette in subtle antique gold zari weave.',
      description: 'Crafted from pure georgette silk yarn, this Khaddi saree offers unmatched drape and graceful fluid movement combined with opulent zari jaal work.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[8], alt: 'Antique Gold Khaddi Banarasi' },
        { url: imgList[9], alt: 'Antique Gold Khaddi Banarasi Drape' },
      ],
    },
    {
      name: 'Vintage Yellow Tanchoi Silk Banarasi Saree',
      category: categoryDocs['Banarasi Sarees']._id,
      price: 24500,
      discountPrice: 21999,
      fabric: 'Tanchoi Silk',
      work: 'Satin Weave Tanchoi',
      origin: 'Varanasi, Uttar Pradesh',
      occasion: ['Casual', 'Festive', 'Office'],
      color: ['Mustard Yellow', 'Maroon'],
      length: 6.3,
      blouseIncluded: true,
      stock: 14,
      sku: 'TANT-BAN-006',
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Soft mustard yellow silk with intricate satin-weave Tanchoi paisley motifs.',
      description: 'Tanchoi is renowned for its smooth texture without raised threads on the reverse. Soft, comfortable, and deeply elegant for all occasions.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[10], alt: 'Yellow Tanchoi Saree' },
        { url: imgList[11], alt: 'Yellow Tanchoi Saree Detail' },
      ],
    },
    {
      name: 'Opulent Violet Shikargah Banarasi Silk Saree',
      category: categoryDocs['Banarasi Sarees']._id,
      price: 64000,
      discountPrice: 58000,
      fabric: 'Katan Silk',
      work: 'Shikargah Brocade',
      origin: 'Varanasi, Uttar Pradesh',
      occasion: ['Bridal', 'Wedding'],
      color: ['Deep Violet', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 5,
      sku: 'TANT-BAN-007',
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Collector’s royal violet saree featuring rare royal hunting scene Shikargah brocade.',
      description: 'Depicting elephants, deer, and royal hunters amidst dense forest vines, this Shikargah saree represents the pinnacle of Banarasi handloom artistry.',
      care: 'Dry clean only. Store wrapped in white cotton cloth.',
      images: [
        { url: imgList[12], alt: 'Violet Shikargah Banarasi Saree' },
        { url: imgList[13], alt: 'Violet Shikargah Detail' },
      ],
    },
    {
      name: 'Peach Coral Shikargah Katan Silk Saree',
      category: categoryDocs['Banarasi Sarees']._id,
      price: 41000,
      discountPrice: 36500,
      fabric: 'Katan Silk',
      work: 'Kadhi Zari',
      origin: 'Varanasi, Uttar Pradesh',
      occasion: ['Festive', 'Wedding'],
      color: ['Peach', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 9,
      sku: 'TANT-BAN-008',
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Soft pastel peach coral shade with glowing champagne gold zari bootis.',
      description: 'A modern pastel interpretation of timeless Banarasi weaving. Subtle, graceful, and perfect for daytime weddings and haldi ceremonies.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[14], alt: 'Peach Coral Banarasi Saree' },
        { url: imgList[15], alt: 'Peach Coral Saree Close-up' },
      ],
    },

    // --- Kanjivaram Silk (9-16) ---
    {
      name: 'Maroon Pure Mulberry Kanchipuram Temple Border Silk Saree',
      category: categoryDocs['Kanjivaram Silk']._id,
      price: 58000,
      discountPrice: 52000,
      fabric: 'Mulberry Silk',
      work: 'Korvai Weave & Pure Zari',
      origin: 'Kanchipuram, Tamil Nadu',
      occasion: ['Wedding', 'Bridal', 'Festive'],
      color: ['Maroon', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 7,
      sku: 'TANT-KAN-001',
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Authentic 3-ply Mulberry silk Kanjivaram with classic grand Korvai temple border.',
      description: 'Woven using the traditional Korvai interlock technique where the body and border are woven separately and joined by hand. Weighs over 800g of pure heavy silk.',
      care: 'Dry clean only. Roll saree to protect pure silver-gold zari.',
      images: [
        { url: imgList[16], alt: 'Maroon Kanjivaram Silk Saree' },
        { url: imgList[17], alt: 'Maroon Kanjivaram Border Detail' },
      ],
    },
    {
      name: 'Peacock Blue & Gold Kanjivaram Silk Saree',
      category: categoryDocs['Kanjivaram Silk']._id,
      price: 49500,
      discountPrice: 44000,
      fabric: 'Mulberry Silk',
      work: 'Zari Annapakshi Motifs',
      origin: 'Kanchipuram, Tamil Nadu',
      occasion: ['Wedding', 'Festive'],
      color: ['Peacock Blue', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 11,
      sku: 'TANT-KAN-002',
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Striking peacock blue body contrasted with heavy gold Zari border and Annapakshi swans.',
      description: 'Featuring auspicious Annapakshi (mythical swan) motifs woven along the pallu and border in test-passed gold zari.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[18], alt: 'Peacock Blue Kanjivaram' },
        { url: imgList[19], alt: 'Peacock Blue Pallu Detail' },
      ],
    },
    {
      name: 'Golden Yellow & Mustard Dual-Tone Kanjivaram Saree',
      category: categoryDocs['Kanjivaram Silk']._id,
      price: 42000,
      discountPrice: 37800,
      fabric: 'Kanjivaram Silk',
      work: 'Mayil (Peacock) Motifs',
      origin: 'Kanchipuram, Tamil Nadu',
      occasion: ['Festive', 'Wedding', 'Daily Wear'],
      color: ['Yellow', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 13,
      sku: 'TANT-KAN-003',
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Luminous dual-tone golden yellow silk saree with traditional contrast rudraksham border.',
      description: 'Spun from heavy grade mulberry silk, glowing with rich yellow hues ideal for auspicious south Indian wedding ceremonies.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[20], alt: 'Yellow Kanjivaram Saree' },
        { url: imgList[21], alt: 'Yellow Kanjivaram Close' },
      ],
    },
    {
      name: 'Deep Crimson & Green Contrast Border Kanjivaram',
      category: categoryDocs['Kanjivaram Silk']._id,
      price: 62000,
      discountPrice: 55000,
      fabric: 'Mulberry Silk',
      work: 'Heavy Zari Pallu',
      origin: 'Kanchipuram, Tamil Nadu',
      occasion: ['Bridal', 'Wedding'],
      color: ['Crimson Red', 'Emerald Green'],
      length: 6.3,
      blouseIncluded: true,
      stock: 6,
      sku: 'TANT-KAN-004',
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Royal bridal crimson red Kanjivaram with classic bottle green contrast pallu.',
      description: 'The ultimate South Indian bridal dream. Features genuine silver thread dipped in 24k gold leaf zari for everlasting sheen.',
      care: 'Dry clean only. Store flat.',
      images: [
        { url: imgList[22], alt: 'Crimson Green Kanjivaram Saree' },
        { url: imgList[23], alt: 'Crimson Green Kanjivaram Pallu' },
      ],
    },
    {
      name: 'Pastel Lavender Silver Zari Kanjivaram Silk Saree',
      category: categoryDocs['Kanjivaram Silk']._id,
      price: 39500,
      discountPrice: 35000,
      fabric: 'Pure Silk',
      work: 'Silver Zari Weave',
      origin: 'Kanchipuram, Tamil Nadu',
      occasion: ['Party', 'Festive'],
      color: ['Lavender', 'Silver'],
      length: 6.3,
      blouseIncluded: true,
      stock: 10,
      sku: 'TANT-KAN-005',
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Modern pastel lavender shade paired with pure silver zari geometric checks.',
      description: 'Brings contemporary aesthetics to traditional Kanjivaram weaving. Subtle, elegant, and ethereal.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[24], alt: 'Lavender Kanjivaram Saree' },
        { url: imgList[25], alt: 'Lavender Kanjivaram Detail' },
      ],
    },
    {
      name: 'Royal Copper Zari Tissue Kanjivaram Saree',
      category: categoryDocs['Kanjivaram Silk']._id,
      price: 51000,
      discountPrice: 45900,
      fabric: 'Tissue Kanjivaram Silk',
      work: 'Copper Zari Weave',
      origin: 'Kanchipuram, Tamil Nadu',
      occasion: ['Wedding', 'Party'],
      color: ['Copper Gold', 'Bronze'],
      length: 6.3,
      blouseIncluded: true,
      stock: 7,
      sku: 'TANT-KAN-006',
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Shimmering metallic copper zari tissue woven into pure silk body.',
      description: 'Exudes vintage metallic glamour. The copper gold sheen captures evening lights brilliantly.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[26], alt: 'Copper Tissue Kanjivaram' },
        { url: imgList[27], alt: 'Copper Tissue Saree Close' },
      ],
    },
    {
      name: 'Off-White & Red Temple Border Muhurtham Kanjivaram',
      category: categoryDocs['Kanjivaram Silk']._id,
      price: 47000,
      discountPrice: 41900,
      fabric: 'Mulberry Silk',
      work: 'Temple Border Korvai',
      origin: 'Kanchipuram, Tamil Nadu',
      occasion: ['Wedding', 'Festive'],
      color: ['Off-White', 'Red'],
      length: 6.3,
      blouseIncluded: true,
      stock: 9,
      sku: 'TANT-KAN-007',
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Sacred off-white ivory body with deep kumkum red temple border.',
      description: 'Ideal for wedding rituals, ceremonies, and traditional occasions. Handcrafted with traditional wooden pit looms.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[28], alt: 'Off White Red Kanjivaram' },
        { url: imgList[29], alt: 'Off White Red Saree Detail' },
      ],
    },
    {
      name: 'Turquoise Teal Floral Lattice Kanjivaram Silk Saree',
      category: categoryDocs['Kanjivaram Silk']._id,
      price: 44000,
      discountPrice: 39000,
      fabric: 'Pure Silk',
      work: 'Zari Lattice Jaal',
      origin: 'Kanchipuram, Tamil Nadu',
      occasion: ['Festive', 'Party', 'Wedding'],
      color: ['Turquoise', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 12,
      sku: 'TANT-KAN-008',
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Vibrant turquoise teal body covered in delicate gold lattice jaal work.',
      description: 'Features fine coin bootas and a heavy pallu portraying lotus motifs in rich gold thread.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[30], alt: 'Turquoise Kanjivaram Saree' },
        { url: imgList[31], alt: 'Turquoise Saree Pallu' },
      ],
    },

    // --- Chanderi & Maheshwari (17-24) ---
    {
      name: 'Pistachio Green Handblock Printed Chanderi Silk Saree',
      category: categoryDocs['Chanderi & Maheshwari']._id,
      price: 14500,
      discountPrice: 12500,
      fabric: 'Chanderi Silk Cotton',
      work: 'Handblock Print & Gold Zari Border',
      origin: 'Chanderi, Madhya Pradesh',
      occasion: ['Casual', 'Office', 'Festive'],
      color: ['Pistachio Green', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 20,
      sku: 'TANT-CHA-001',
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Breathable pistachio green Chanderi with traditional Bagru floral block prints.',
      description: 'Sheer, lightweight, and elegant. Spun from hand-picked cotton and fine silk warp, adorned with characteristic Chanderi gold borders.',
      care: 'Dry clean recommended. Gentle handwash in cold water.',
      images: [
        { url: imgList[32], alt: 'Pistachio Green Chanderi Saree' },
        { url: imgList[33], alt: 'Pistachio Chanderi Detail' },
      ],
    },
    {
      name: 'Maheshwari Silk Tissue Reversible Border Saree',
      category: categoryDocs['Chanderi & Maheshwari']._id,
      price: 16800,
      discountPrice: 14900,
      fabric: 'Maheshwari Silk Cotton',
      work: 'Bugdi Reversible Border',
      origin: 'Maheshwar, Madhya Pradesh',
      occasion: ['Office', 'Casual', 'Party'],
      color: ['Powder Blue', 'Silver'],
      length: 6.3,
      blouseIncluded: true,
      stock: 18,
      sku: 'TANT-CHA-002',
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Powder blue Maheshwari saree with signature reversible Bugdi zari border.',
      description: 'Commissioned under the patronage of Maharani Ahilyabai Holkar. Reversible border allows styling on both sides.',
      care: 'Gentle handwash with mild silk detergent.',
      images: [
        { url: imgList[34], alt: 'Powder Blue Maheshwari Saree' },
        { url: imgList[35], alt: 'Maheshwari Border Detail' },
      ],
    },
    {
      name: 'Ivory Gold Coin Bootti Pure Chanderi Silk Saree',
      category: categoryDocs['Chanderi & Maheshwari']._id,
      price: 19500,
      discountPrice: 17200,
      fabric: 'Chanderi Silk',
      work: 'Ashrafi (Coin) Zari Bootti',
      origin: 'Chanderi, Madhya Pradesh',
      occasion: ['Festive', 'Party'],
      color: ['Ivory', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 14,
      sku: 'TANT-CHA-003',
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Serene ivory white sheer silk with handwoven gold Ashrafi coin motifs.',
      description: 'Refined royal elegance. The golden coins shimmer subtly against the translucent ivory silk backdrop.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[36], alt: 'Ivory Chanderi Silk Saree' },
        { url: imgList[37], alt: 'Ivory Chanderi Close-up' },
      ],
    },
    {
      name: 'Peach Chanderi Katan Silk Saree with Zari Border',
      category: categoryDocs['Chanderi & Maheshwari']._id,
      price: 18000,
      discountPrice: 15900,
      fabric: 'Chanderi Katan',
      work: 'Eknali Border',
      origin: 'Chanderi, Madhya Pradesh',
      occasion: ['Festive', 'Casual'],
      color: ['Peach', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 16,
      sku: 'TANT-CHA-004',
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Delicate peach shade with traditional narrow Eknali gold woven border.',
      description: 'Woven with high twist silk yarns creating a crisp texture that holds its form effortlessly.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[38], alt: 'Peach Chanderi Saree' },
        { url: imgList[39], alt: 'Peach Chanderi Detail' },
      ],
    },
    {
      name: 'Black & Gold Narmada Border Maheshwari Saree',
      category: categoryDocs['Chanderi & Maheshwari']._id,
      price: 15500,
      discountPrice: 13800,
      fabric: 'Maheshwari Silk',
      work: 'Narmada Wave Border',
      origin: 'Maheshwar, Madhya Pradesh',
      occasion: ['Party', 'Casual'],
      color: ['Black', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 19,
      sku: 'TANT-CHA-005',
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Classic black Maheshwari silk with Narmada river wave border motifs.',
      description: 'Striking black and gold contrast with geometric motifs inspired by Maheshwar fort carvings.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[40], alt: 'Black Maheshwari Saree' },
        { url: imgList[41], alt: 'Black Maheshwari Closeup' },
      ],
    },
    {
      name: 'Coral Pink Chanderi Pattu Silk Saree',
      category: categoryDocs['Chanderi & Maheshwari']._id,
      price: 21000,
      discountPrice: 18500,
      fabric: 'Chanderi Pattu',
      work: 'Adda Work & Zari',
      origin: 'Chanderi, Madhya Pradesh',
      occasion: ['Festive', 'Wedding'],
      color: ['Coral Pink', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 11,
      sku: 'TANT-CHA-006',
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Vibrant coral pink Chanderi Pattu silk with heavy zari woven pallu.',
      description: 'Combines the lightness of Chanderi with the rich luster of South Pattu silk yarns.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[42], alt: 'Coral Pink Chanderi Saree' },
        { url: imgList[43], alt: 'Coral Pink Detail' },
      ],
    },
    {
      name: 'Mint Green Tissue Chanderi Saree',
      category: categoryDocs['Chanderi & Maheshwari']._id,
      price: 17500,
      discountPrice: 15200,
      fabric: 'Tissue Chanderi',
      work: 'Metallic Zari Weave',
      origin: 'Chanderi, Madhya Pradesh',
      occasion: ['Party', 'Festive'],
      color: ['Mint Green', 'Silver'],
      length: 6.3,
      blouseIncluded: true,
      stock: 13,
      sku: 'TANT-CHA-007',
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Refreshing mint green tissue Chanderi glowing with subtle silver threads.',
      description: 'Translucent metallic sheen ideal for modern summer festive celebrations.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[44], alt: 'Mint Green Chanderi' },
        { url: imgList[45], alt: 'Mint Green Saree Close' },
      ],
    },
    {
      name: 'Mustard Yellow Chanderi Silk Cotton Saree',
      category: categoryDocs['Chanderi & Maheshwari']._id,
      price: 12800,
      discountPrice: 11200,
      fabric: 'Silk Cotton',
      work: 'Zari Border',
      origin: 'Chanderi, Madhya Pradesh',
      occasion: ['Casual', 'Office', 'Festive'],
      color: ['Mustard', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 22,
      sku: 'TANT-CHA-008',
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Bright sunny mustard yellow silk cotton saree for comfortable daily luxury.',
      description: 'Drapes effortlessly without clinging. Features traditional Chanderi gold border.',
      care: 'Handwash gently in cold water.',
      images: [
        { url: imgList[46], alt: 'Mustard Chanderi Saree' },
        { url: imgList[47], alt: 'Mustard Chanderi Detail' },
      ],
    },

    // --- Organza & Tussar (25-32) ---
    {
      name: 'Hand-Painted Floral Organza Silk Saree in Soft Rose',
      category: categoryDocs['Organza & Tussar']._id,
      price: 22500,
      discountPrice: 19800,
      fabric: 'Organza Silk',
      work: 'Hand-Painted Floral Art & Gotapatti',
      origin: 'Jaipur, Rajasthan',
      occasion: ['Party', 'Festive', 'Casual'],
      color: ['Dusty Rose', 'Pastel Pink'],
      length: 6.3,
      blouseIncluded: true,
      stock: 12,
      sku: 'TANT-ORG-001',
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Ethereal dusty rose organza silk hand-painted with pastel botanical roses.',
      description: 'Each saree is individually painted by Jaipur artists using water-resistant fabric paints and edged with delicate Gota Patti border work.',
      care: 'Dry clean only. Handle with extreme care.',
      images: [
        { url: imgList[48], alt: 'Hand Painted Organza Saree' },
        { url: imgList[49], alt: 'Organza Floral Detail' },
      ],
    },
    {
      name: 'Natural Honey Bhagalpuri Tussar Silk Saree',
      category: categoryDocs['Organza & Tussar']._id,
      price: 18900,
      discountPrice: 16500,
      fabric: 'Pure Wild Tussar Silk',
      work: 'Kantha Hand Embroidery',
      origin: 'Bhagalpur, Bihar',
      occasion: ['Casual', 'Office', 'Festive'],
      color: ['Natural Beige', 'Honey Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 15,
      sku: 'TANT-ORG-002',
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Textured unbleached honey Tussar silk detailed with running Kantha embroidery.',
      description: 'Harvested from wild silk moths in the forests of Bihar, offering a distinctive rich matte texture and royal earthy drape.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[50], alt: 'Bhagalpuri Tussar Silk Saree' },
        { url: imgList[51], alt: 'Tussar Kantha Embroidery Detail' },
      ],
    },
    {
      name: 'Sage Green Sheer Organza with Embroidered Border',
      category: categoryDocs['Organza & Tussar']._id,
      price: 19800,
      discountPrice: 17400,
      fabric: 'Pure Organza',
      work: 'Thread Embroidery & Scallop Border',
      origin: 'Varanasi, Uttar Pradesh',
      occasion: ['Party', 'Festive'],
      color: ['Sage Green', 'White'],
      length: 6.3,
      blouseIncluded: true,
      stock: 14,
      sku: 'TANT-ORG-003',
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Refreshing sage green organza featuring intricate white scalloped threadwork borders.',
      description: 'Crisp and voluminous silhouette that creates an enchanting contemporary ethnic statement.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[52], alt: 'Sage Green Organza Saree' },
        { url: imgList[53], alt: 'Sage Green Scallop Border' },
      ],
    },
    {
      name: 'Charcoal Black Tussar Ghicha Silk Saree',
      category: categoryDocs['Organza & Tussar']._id,
      price: 21500,
      discountPrice: 18900,
      fabric: 'Ghicha Tussar Silk',
      work: 'Tribal Handblock Print',
      origin: 'Chhattisgarh',
      occasion: ['Casual', 'Party', 'Office'],
      color: ['Charcoal Black', 'Copper'],
      length: 6.3,
      blouseIncluded: true,
      stock: 10,
      sku: 'TANT-ORG-004',
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Rustic charcoal black Ghicha silk with earthy tribal geometric block motifs.',
      description: 'Ghicha yarn provides an organic uneven slub texture that softens beautifully with every wear.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[54], alt: 'Charcoal Tussar Ghicha Saree' },
        { url: imgList[55], alt: 'Ghicha Saree Close' },
      ],
    },
    {
      name: 'Powder Pink Printed Organza Silk Saree',
      category: categoryDocs['Organza & Tussar']._id,
      price: 16500,
      discountPrice: 14200,
      fabric: 'Organza Silk',
      work: 'Digital Floral Print & Zari Highlights',
      origin: 'Surat, Gujarat',
      occasion: ['Casual', 'Party'],
      color: ['Powder Pink', 'Pastel Green'],
      length: 6.3,
      blouseIncluded: true,
      stock: 18,
      sku: 'TANT-ORG-005',
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Dreamy powder pink organza featuring romantic watercolor floral prints.',
      description: 'Ultra-lightweight drape adorned with subtle sequin edging for evening soirées.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[56], alt: 'Powder Pink Organza Saree' },
        { url: imgList[57], alt: 'Powder Pink Floral Detail' },
      ],
    },
    {
      name: 'Mustard Gold Tussar Georgette Saree',
      category: categoryDocs['Organza & Tussar']._id,
      price: 24000,
      discountPrice: 21000,
      fabric: 'Tussar Georgette',
      work: 'Zari Weave',
      origin: 'Bhagalpur, Bihar',
      occasion: ['Festive', 'Wedding'],
      color: ['Mustard Gold', 'Bronze'],
      length: 6.3,
      blouseIncluded: true,
      stock: 9,
      sku: 'TANT-ORG-006',
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Rich golden mustard tussar georgette silk with textured rustic body.',
      description: 'Blends the flowing drape of georgette with the royal texture of raw Tussar silk.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[58], alt: 'Mustard Tussar Georgette' },
        { url: imgList[59], alt: 'Mustard Saree Detail' },
      ],
    },
    {
      name: 'Sky Blue Floral Handblock Printed Organza',
      category: categoryDocs['Organza & Tussar']._id,
      price: 17800,
      discountPrice: 15500,
      fabric: 'Organza',
      work: 'Block Print',
      origin: 'Jaipur, Rajasthan',
      occasion: ['Casual', 'Festive'],
      color: ['Sky Blue', 'White'],
      length: 6.3,
      blouseIncluded: true,
      stock: 16,
      sku: 'TANT-ORG-007',
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Breezy sky blue organza with serene white lotus block prints.',
      description: 'Brings daytime elegance with light pastel color palettes.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[60], alt: 'Sky Blue Organza Saree' },
        { url: imgList[61], alt: 'Sky Blue Detail' },
      ],
    },
    {
      name: 'Terracotta Red Handwoven Tussar Silk Saree',
      category: categoryDocs['Organza & Tussar']._id,
      price: 26000,
      discountPrice: 22800,
      fabric: 'Pure Tussar',
      work: 'Katha Weave',
      origin: 'West Bengal',
      occasion: ['Festive', 'Wedding'],
      color: ['Terracotta Red', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 8,
      sku: 'TANT-ORG-008',
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Rich earthy terracotta red Tussar silk featuring gold weave borders.',
      description: 'Traditional Bengali handloom heritage celebrating earthy natural dyes.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[62], alt: 'Terracotta Tussar Saree' },
        { url: imgList[63], alt: 'Terracotta Detail' },
      ],
    },

    // --- Cotton & Linen (33-40) ---
    {
      name: 'Bengal Jamdani Handloom Cotton Saree in Pure White',
      category: categoryDocs['Cotton & Linen']._id,
      price: 9800,
      discountPrice: 8500,
      fabric: 'Mulmul Cotton',
      work: 'Dhakai Jamdani Weave',
      origin: 'Phulia, West Bengal',
      occasion: ['Casual', 'Office', 'Festive'],
      color: ['White', 'Red'],
      length: 6.3,
      blouseIncluded: true,
      stock: 25,
      sku: 'TANT-COT-001',
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Classic white Dhakai Jamdani with red geometric floral body motifs.',
      description: 'UNESCO recognized intangible cultural heritage. Woven using supple bamboo needles without any modern machinery.',
      care: 'Gentle handwash in cold water with mild liquid soap.',
      images: [
        { url: imgList[64], alt: 'Bengal Jamdani Cotton Saree' },
        { url: imgList[65], alt: 'Dhakai Jamdani Detail' },
      ],
    },
    {
      name: 'Natural Organic Linen Silk Saree with Zari Border',
      category: categoryDocs['Cotton & Linen']._id,
      price: 11500,
      discountPrice: 9900,
      fabric: 'Pure Linen Silk',
      work: 'Silver Zari Selvedge',
      origin: 'Bhagalpur, Bihar',
      occasion: ['Office', 'Casual', 'Party'],
      color: ['Oatmeal Beige', 'Silver'],
      length: 6.3,
      blouseIncluded: true,
      stock: 20,
      sku: 'TANT-COT-002',
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Breathable 80-count natural linen silk with sleek silver zari selvedge.',
      description: 'Combines the crisp texture of European flax linen with the soft shine of mulberry silk.',
      care: 'Gentle handwash or dry clean.',
      images: [
        { url: imgList[66], alt: 'Linen Silk Saree' },
        { url: imgList[67], alt: 'Linen Silk Border Detail' },
      ],
    },
    {
      name: 'Indigo Blue Ajrakh Block Printed Cotton Saree',
      category: categoryDocs['Cotton & Linen']._id,
      price: 7900,
      discountPrice: 6900,
      fabric: 'Pure Malmal Cotton',
      work: '16-Step Ajrakh Block Print',
      origin: 'Kutch, Gujarat',
      occasion: ['Casual', 'Office', 'Daily Wear'],
      color: ['Indigo Blue', 'Madder Red'],
      length: 6.3,
      blouseIncluded: true,
      stock: 30,
      sku: 'TANT-COT-003',
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Authentic natural indigo Ajrakh handblock printed soft mulmul cotton saree.',
      description: 'Crafted using natural vegetable dyes, indigo, and madder root in 16 laborious washing and printing stages.',
      care: 'Wash separately in cold water with mild detergent.',
      images: [
        { url: imgList[68], alt: 'Indigo Ajrakh Cotton Saree' },
        { url: imgList[69], alt: 'Ajrakh Block Print Closeup' },
      ],
    },
    {
      name: 'Pastel Mint Linen Saree with Jamdani Pallu',
      category: categoryDocs['Cotton & Linen']._id,
      price: 13500,
      discountPrice: 11800,
      fabric: 'Pure Linen',
      work: 'Jamdani Motif Pallu',
      origin: 'Bengal',
      occasion: ['Office', 'Casual', 'Festive'],
      color: ['Mint Green', 'White'],
      length: 6.3,
      blouseIncluded: true,
      stock: 18,
      sku: 'TANT-COT-004',
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Soothing mint green pure linen saree with intricate white Jamdani weave pallu.',
      description: 'Ultra-cool comfort for tropical summers with high-end artisanal appeal.',
      care: 'Dry clean recommended.',
      images: [
        { url: imgList[70], alt: 'Mint Linen Saree' },
        { url: imgList[71], alt: 'Mint Linen Detail' },
      ],
    },
    {
      name: 'Mustard Yellow Chettinad Cotton Saree',
      category: categoryDocs['Cotton & Linen']._id,
      price: 6500,
      discountPrice: 5500,
      fabric: 'Chettinad Cotton',
      work: 'Temple Checks & Zari',
      origin: 'Tamil Nadu',
      occasion: ['Daily Wear', 'Casual', 'Office'],
      color: ['Mustard', 'Maroon'],
      length: 6.3,
      blouseIncluded: true,
      stock: 28,
      sku: 'TANT-COT-005',
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'Traditional mustard yellow Chettinad heavy cotton saree with thick zari borders.',
      description: 'Sturdy, long-lasting South Indian cotton weave known for rich colorfast dyes and crisp structure.',
      care: 'Handwash in cold water.',
      images: [
        { url: imgList[72], alt: 'Chettinad Cotton Saree' },
        { url: imgList[73], alt: 'Chettinad Saree Detail' },
      ],
    },
    {
      name: 'Kota Doria Silk Cotton Saree with Zari Bootis',
      category: categoryDocs['Cotton & Linen']._id,
      price: 8900,
      discountPrice: 7800,
      fabric: 'Kota Doria',
      work: 'Khat Square Weave & Zari',
      origin: 'Kota, Rajasthan',
      occasion: ['Casual', 'Office', 'Festive'],
      color: ['Lemon Yellow', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 22,
      sku: 'TANT-COT-006',
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Weightless lemon yellow Kota Doria saree with characteristic square Khat grid weave.',
      description: 'Woven with silk and cotton threads to produce small square patterns known as Khats.',
      care: 'Gentle handwash.',
      images: [
        { url: imgList[74], alt: 'Kota Doria Saree' },
        { url: imgList[75], alt: 'Kota Doria Detail' },
      ],
    },
    {
      name: 'Royal Heritage Bridal Crimson & Gold Zari Brocade Saree',
      category: categoryDocs['Heritage Bridal']._id,
      price: 85000,
      discountPrice: 76500,
      fabric: 'Pure Katan Silk',
      work: '24K Gold Plated Zari & Meenakari',
      origin: 'Varanasi, Uttar Pradesh',
      occasion: ['Bridal', 'Wedding'],
      color: ['Bridal Crimson', 'Pure Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 3,
      sku: 'TANT-BRD-001',
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      shortDescription: 'The ultimate royal bridal trousseau saree handcrafted over 90 days with 24k gold leaf zari.',
      description: 'An unparalleled heirloom investment piece. Features royal court motifs, elephants, and lotus medallions. Includes velvet storage box.',
      care: 'Professional museum archival dry clean only.',
      images: [
        { url: imgList[76], alt: 'Heritage Bridal Crimson Saree' },
        { url: imgList[77], alt: 'Heritage Bridal Pallu Detail' },
      ],
    },
    {
      name: 'Gold & Ivory Royal Temple Kanjivaram Bridal Saree',
      category: categoryDocs['Heritage Bridal']._id,
      price: 72000,
      discountPrice: 65000,
      fabric: 'Heavy Mulberry Silk',
      work: 'Pure Silver-Gold Korvai',
      origin: 'Kanchipuram, Tamil Nadu',
      occasion: ['Bridal', 'Wedding'],
      color: ['Ivory', 'Gold'],
      length: 6.3,
      blouseIncluded: true,
      stock: 4,
      sku: 'TANT-BRD-002',
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      shortDescription: 'Magnificent ivory & gold Kanjivaram bridal saree with intricate temple gopuram motifs.',
      description: 'Woven for grand Muhurtham wedding vows. Weighs 950 grams of dense 3-ply mulberry silk and pure zari.',
      care: 'Dry clean only.',
      images: [
        { url: imgList[78], alt: 'Gold Ivory Kanjivaram Bridal' },
        { url: imgList[79], alt: 'Gold Ivory Bridal Detail' },
      ],
    },
  ];

  for (const prod of products) {
    const createdProduct = await Product.create(prod);
    console.log(`✨ Added Product [${createdProduct.sku}]: ${createdProduct.name}`);
  }

  console.log('\n🎉 Successfully seeded 40 realistic luxury saree products into database!');
}

module.exports = seedDatabase;

if (require.main === module) {
  seedDatabase(true)
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('❌ Seeding failed:', err);
      process.exit(1);
    });
}
